import pandas as pd
from sqlalchemy import select
from sqlalchemy.orm import Session
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

from app.controllers.insights_controller import add_new_insight_investigator
from app.core.database import SessionLocal # Usaremos isso para rotinas automáticas
from app.models.expense import Expense
from app.models.expense_category import Expense_category
from app.models.user import User
from app.models.ia_insights import Ia_insights
from app.services.ai_processor import generate_behavioral_insights


def get_data_users(db: Session):
    try:
        stmt = (select(User.id))
        ids_of_users = db.execute(stmt).scalars().all()
        debug_print(is_show=True, text=f"IDs of users fetched: {ids_of_users}")
        return ids_of_users
    except Exception as e:
        print(f"Error occurred while fetching user data: {e}")
        return []
    

def get_expenses_by_user_id(user_id: int, db: Session):
    try:
        stmt = select(Expense.date, Expense_category.name.label('category_name')).join(
            Expense_category, Expense.category == Expense_category.id
        ).where(
            Expense.user_id == user_id,
            Expense.type_expense == False,
            Expense.is_activated == True
        )
        
        transacoes = db.execute(stmt).all()
        debug_print(is_show=True, text=f"Fetched {len(transacoes)} transactions for user {user_id}")
        return transacoes
    except Exception as e:
        print(f"Error occurred while fetching expenses for user {user_id}: {e}")
        return []


def training_model():
    
    db = SessionLocal() 
    try:
        ids_users = get_data_users(db)
        data_for_gemini = []

        for id in ids_users:
            transactions_user = get_expenses_by_user_id(id, db)
            if not transactions_user or len(transactions_user) < 5:
                print(f"⚠️ Usuário {id} tem poucas ou nenhuma despesa, pulando...")
                continue
            df = pd.DataFrame(transactions_user, columns=['date', 'category_name'])
            df['date'] = pd.to_datetime(df['date']).dt.date
            df = df.dropna(subset=['category_name'])
            groups = df.groupby('date')['category_name'].apply(list).tolist()

            if len(groups) < 5:
                print(f"⚠️ Usuário {id} tem poucas transações agrupadas, pulando...")
                continue

            te = TransactionEncoder()
            te_ary = te.fit(groups).transform(groups)
            df_ia = pd.DataFrame(te_ary, columns=te.columns_)
            debug_print(is_show=True, text=f"Transaction encoding completed for user {id} with {len(df_ia)} rows.")
            try:
                frequent_itemsets = apriori(df_ia, min_support=0.05, use_colnames=True)
                rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.60)
            except Exception as e:
                print(f"🚨 Erro ao rodar Apriori para usuário {id}: {e}")
                continue

            if rules.empty:
                continue

            rules = rules.sort_values(by=['lift', 'confidence'], ascending=[False, False])
            best_rule = rules.head(1).iloc[0]

            if best_rule['lift'] > 1:
                cause = list(best_rule['antecedents'])[0]
                consequence = list(best_rule['consequents'])[0]

                data_for_gemini.append({
                    'user_id': id,
                    'rule': f"{cause} -> {consequence}"
                })

        if data_for_gemini:
            print(f'✅ Regras geradas para {len(data_for_gemini)} usuários. Enviando para o Gemini...')
            insights_text = generate_behavioral_insights(data_for_gemini)
            debug_print(is_show=True, text=f"Insights generated by Gemini: {insights_text}")
            for item in insights_text:
                add_new_insight_investigator(
                    user_id=item['user_id'],
                    title="Comportamento Financeiro",
                    text_content=item['insight'],
                    db=db
                )
        else:
            print("⚠️ Nenhuma regra forte encontrada para nenhum usuário desta vez.")

    except Exception as e:
        db.rollback() # Se der erro grave, cancela tudo para não sujar o banco
        print(f"🚨 Erro crítico na pipeline: {e}")
    finally:
        db.close() # Sempre fecha o telefone na cara do banco de dados no final!


def debug_print(is_show: bool = False, text: str = ""):
    if is_show:
        print(f"Debug mode is ON - {text}")
    else:
        print("Debug mode is OFF")