"""add is_deleted to expense table

Revision ID: 0a2cab5554c6
Revises: a96ae9f06d93
Create Date: 2026-08-09 23:08:03.080840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2cab5554c6'
down_revision: Union[str, Sequence[str], None] = 'a96ae9f06d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('expenses_fixed', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses_fixed', 'is_deleted')
    op.drop_column('expense', 'is_deleted')
    # ### end Alembic commands ###
