"""added device id to table user credentials

Revision ID: 134f44b6d258
Revises: 23dbeba3ac9b
Create Date: 2026-02-16 21:54:49.085699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134f44b6d258'
down_revision: Union[str, Sequence[str], None] = '23dbeba3ac9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('device_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'device_id')
    # ### end Alembic commands ###
