"""altered name of column of table expenses_fixed

Revision ID: 2314c29556ea
Revises: 351fa321c61f
Create Date: 2026-01-22 13:08:36.384381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2314c29556ea'
down_revision: Union[str, Sequence[str], None] = '351fa321c61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_fixed', sa.Column('category', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('expenses_fixed_category_id_fkey'), 'expenses_fixed', type_='foreignkey')
    op.create_foreign_key(None, 'expenses_fixed', 'expenses_category', ['category'], ['id'])
    op.drop_column('expenses_fixed', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_fixed', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses_fixed', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_fixed_category_id_fkey'), 'expenses_fixed', 'expenses_category', ['category_id'], ['id'])
    op.drop_column('expenses_fixed', 'category')
    # ### end Alembic commands ###
