"""added new columns

Revision ID: 351fa321c61f
Revises: 8f9b11bdfcf2
Create Date: 2026-01-20 00:28:50.397034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351fa321c61f'
down_revision: Union[str, Sequence[str], None] = '8f9b11bdfcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('otp_code', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('second_factor_auth', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'second_factor_auth')
    op.drop_column('user', 'otp_code')
    op.drop_column('expense', 'name')
    # ### end Alembic commands ###
