"""added column expires_at on table user_temp

Revision ID: 3b558fae8a00
Revises: 1d3d387b6cd8
Create Date: 2026-02-26 01:51:48.218728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b558fae8a00'
down_revision: Union[str, Sequence[str], None] = '1d3d387b6cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_temp', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_temp', 'expires_at')
    # ### end Alembic commands ###
