"""change table of credential table for testing

Revision ID: 48682800b766
Revises: 134f44b6d258
Create Date: 2026-02-19 23:37:24.761355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48682800b766'
down_revision: Union[str, Sequence[str], None] = '134f44b6d258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credentials', 'credential_id',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_credentials', 'credential_id',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
