"""added new columns to expense_fixed table

Revision ID: 70dfddfe64a9
Revises: 09eb12884c0a
Create Date: 2026-01-07 00:07:01.167934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dfddfe64a9'
down_revision: Union[str, Sequence[str], None] = '09eb12884c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_fixed', sa.Column('type_expense', sa.Boolean(), nullable=False))
    op.add_column('expenses_fixed', sa.Column('installments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses_fixed', 'installments_count')
    op.drop_column('expenses_fixed', 'type_expense')
    # ### end Alembic commands ###
