"""added new columns to expense_fixed table

Revision ID: 8f9b11bdfcf2
Revises: 70dfddfe64a9
Create Date: 2026-01-08 00:54:59.666243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9b11bdfcf2'
down_revision: Union[str, Sequence[str], None] = '70dfddfe64a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_fixed', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses_fixed', 'description')
    # ### end Alembic commands ###
