"""add ondelete on table expense

Revision ID: a1ef69ccf5ae
Revises: 6768d2284906
Create Date: 2026-03-16 09:32:28.542608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ef69ccf5ae'
down_revision: Union[str, Sequence[str], None] = '6768d2284906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_fixed_expense_id_fkey'), 'expense', type_='foreignkey')
    op.create_foreign_key(None, 'expense', 'expenses_fixed', ['fixed_expense_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_foreign_key(op.f('expense_fixed_expense_id_fkey'), 'expense', 'expenses_fixed', ['fixed_expense_id'], ['id'])
    # ### end Alembic commands ###
