"""added table ia balance predict

Revision ID: a96ae9f06d93
Revises: db96a8f12313
Create Date: 2026-04-19 21:44:18.097310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96ae9f06d93'
down_revision: Union[str, Sequence[str], None] = 'db96a8f12313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('real_balance', sa.Float(), nullable=True),
    sa.Column('predicted_balance', sa.Float(), nullable=True),
    sa.Column('band_min', sa.Float(), nullable=True),
    sa.Column('band_max', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_date', name='uq_user_target_date')
    )
    op.create_index(op.f('ix_balance_forecast_id'), 'balance_forecast', ['id'], unique=False)
    op.create_index(op.f('ix_balance_forecast_user_id'), 'balance_forecast', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_forecast_user_id'), table_name='balance_forecast')
    op.drop_index(op.f('ix_balance_forecast_id'), table_name='balance_forecast')
    op.drop_table('balance_forecast')
    # ### end Alembic commands ###
