"""changed column otp code to otp_code_recovery_password

Revision ID: b9f844e52561
Revises: 3b558fae8a00
Create Date: 2026-02-28 16:35:25.608071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f844e52561'
down_revision: Union[str, Sequence[str], None] = '3b558fae8a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code_recovery_password', sa.Integer(), nullable=True))
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_code_recovery_password')
    # ### end Alembic commands ###
