"""change table Expense category to not name with unique is true propertie

Revision ID: ccb647ea390b
Revises: 8a1fcf0718f7
Create Date: 2026-02-02 00:37:14.715332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb647ea390b'
down_revision: Union[str, Sequence[str], None] = '8a1fcf0718f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_category_name_key'), 'expenses_category', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('expenses_category_name_key'), 'expenses_category', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
