"""added column otp_code_recovery_password_expires_at on table user

Revision ID: e3625951dedb
Revises: b9f844e52561
Create Date: 2026-02-28 18:55:23.385324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3625951dedb'
down_revision: Union[str, Sequence[str], None] = 'b9f844e52561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code_recovery_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_code_recovery_expires_at')
    # ### end Alembic commands ###
