"""add current challenge to users table, add credential table

Revision ID: e9c4ceed1ff7
Revises: f657de8513eb
Create Date: 2026-02-08 22:04:54.962555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c4ceed1ff7'
down_revision: Union[str, Sequence[str], None] = 'f657de8513eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_chalenge', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_chalenge')
    # ### end Alembic commands ###
