"""added balance column to mapping expense fixed in table expense

Revision ID: f6946644eec0
Revises: e8d9f9930db6
Create Date: 2026-02-01 14:02:55.069786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6946644eec0'
down_revision: Union[str, Sequence[str], None] = 'e8d9f9930db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('fixed_expense_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'expenses_fixed', ['fixed_expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'fixed_expense_id')
    # ### end Alembic commands ###
