"""added column payment method to Expenses_fixed table

Revision ID: fe2f2a9a39d5
Revises: 48682800b766
Create Date: 2026-02-25 10:28:00.556905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2f2a9a39d5'
down_revision: Union[str, Sequence[str], None] = '48682800b766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_fixed', sa.Column('payment_method', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses_fixed', 'payment_method')
    # ### end Alembic commands ###
